#网站图标
favicon: /image/lbxx.png

#头像
avatar:
  img: /image/lbxx.png


# Inject
# Insert the code to head (before '</head>' tag) and the bottom (before '</body>' tag)
inject:
  head:
    - <link rel="stylesheet" href="/styles/main.css">
    - <script src="https://cdn.bootcss.com/jquery/3.4.1/jquery.min.js"></script>
  bottom:
    - <script src="/styles/fish.js"></script>
